#!/bin/bash -p 

trap 'eval rm -f ${T}? /tmp/golden*$$ /tmp/output$$ /tmp/err$$' 0
trap exit 2 15

TEST_DIR=${TEST_DIR:-/mnt/img}
T=$TEST_DIR/testfile$$.

# make a file
dd if=/dev/zero of=${T}0 count=2048 2>/dev/null

case `uname` in
Linux)  CP="cp --reflink" ;;
Darwin) CP="cp -c" ;;
esac

# clone it a few times
$CP ${T}0 ${T}1 # same
$CP ${T}0 ${T}2 ; echo foo | dd of=${T}2 bs=1 seek=500000 conv=notrunc 2>/dev/null   # one change
$CP ${T}2 ${T}3 ; echo bar | dd of=${T}3 bs=1 seek=999000 conv=notrunc 2>/dev/null   # two changes from ${T}0
$CP ${T}0 ${T}4 ; echo -n foo >> ${T}4  # longer
$CP ${T}0 ${T}5 ; echo -n bar >> ${T}5  # longer but different
$CP ${T}0 ${T}6 ; echo -n barf >> ${T}6 # longest

FAILED=0

start() {
    echo -n Comparing: $* ' : '
    GOOD=1
}
    
fail() {
    GOOD=0 FAILED=1
    echo "Failed : $3"
    if [ $# -eq 5 ]
    then echo diff cmp vs ccmp ; diff $4 $5
    fi
    echo
}

# compare and check output against cmp

# flags:
cat <<xxx |

-b
-l
-s
-bl
xxx
while read args
do
	cat <<xxx |
${T}0 ${T}1
${T}0 ${T}2
${T}0 ${T}3
${T}3 ${T}4
${T}4 ${T}5
xxx
	while read f g
	do
		start $args $f $g 
		rm -f /tmp/golden$$ /tmp/golden-err$$ /tmp/output$$ /tmp/err$$
		cmp $args $f $g >/tmp/golden$$ 2>/tmp/golden-err$$
		CMPEXIT=$?
		ccmp $args $f $g >/tmp/output$$ 2>/tmp/err$$
		CCMPEXIT=$?
		if [ $CCMPEXIT -ne $CMPEXIT ]
		then fail $f $g "exit status differs ($CMPEXIT for cmp, $CCMPEXIT for ccmp)" 
		fi
		if ! cmp -s /tmp/golden$$ /tmp/output$$ 
		then fail $f $g  "stdout differs" /tmp/golden$$ /tmp/output$$
		fi
		if ! cmp -s /tmp/golden-err$$ /tmp/err$$
		then fail $f $g "stderr differs" /tmp/golden-err$$ /tmp/err$$
		fi
		if [[ $GOOD ]]
		then echo Passed
		fi
	done
done

exit $FAILED
